version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  api:
    build:
      context: ../backend
    env_file: ../.env.example
    volumes:
      - ../backend/app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  worker:
    build:
      context: ../backend
    command: celery -A app.workers worker --loglevel=info
    env_file: ../.env.example
    depends_on:
      - api
      - redis
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=${API_URL}
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    command: npm run dev -- --host 0.0.0.0

volumes:
  db_data:
